# Generated by Django 3.1.7 on 2021-03-02 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='type',
            field=models.CharField(choices=[('CIT', 'Citoyen'), ('C_ADMIN', 'Center_admin'), ('ADMIN', 'Admin')], default='CIT', max_length=50),
        ),
        migrations.CreateModel(
            name='Citoyen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CID', models.CharField(max_length=8, unique=True)),
                ('cov_19', models.BooleanField(default=False)),
                ('date_N', models.DateField()),
                ('address', models.CharField(max_length=60)),
                ('phone', models.IntegerField(max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
