# Generated by Django 3.1.7 on 2021-03-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210302_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citoyen',
            name='phone',
            field=models.IntegerField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
