# Generated by Django 3.1.7 on 2021-03-03 00:06

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210303_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citoyen',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+212707070707', max_length=128, region=None),
        ),
    ]
