# Generated by Django 3.1.7 on 2021-03-03 00:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210303_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citoyen',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
