# Generated by Django 3.1.7 on 2021-03-09 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_useraccount_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.centre'),
        ),
        migrations.AlterField(
            model_name='centre',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RDV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centers', models.CharField(choices=[(1, 'Moulay')], max_length=80)),
                ('is_pass', models.BooleanField(default=False)),
                ('citoyen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.citoyen')),
            ],
        ),
    ]
