# Generated by Django 3.1.7 on 2021-03-09 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210309_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdv',
            name='centers',
        ),
        migrations.AddField(
            model_name='rdv',
            name='date_RDV',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
