# Generated by Django 3.1.7 on 2021-03-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_citoyen_ramid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citoyen',
            name='RAMID',
            field=models.CharField(blank=True, default=0, max_length=10, null=True, unique=True),
        ),
    ]
